name: roommate_app
description: A new Flutter project for managing shared living spaces.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted to a common modern Flutter SDK range

dependencies:
  flutter:
    sdk: flutter

  # Core Functionalities
  sqflite: ^2.3.0 # Example version, replace with latest if known
  nearby_connections: ^1.1.0 # Example version
  # Replaced admob_flutter with google_mobile_ads and added flutter_unity_ads
  google_mobile_ads: ^5.1.0 # Official Google Mobile Ads plugin
  flutter_unity_ads: ^2.2.0 # Example version for Unity Ads
  flutter_local_notifications: ^16.3.0 # Example version
  path_provider: ^2.1.1 # Example version
  encrypt: ^5.0.3 # Example version
  fl_chart: ^0.66.0 # Example version
  shared_preferences: ^2.2.2 # Example version
  wifi_info_flutter: ^2.0.2 # Example version
  qr_flutter: ^4.1.0 # Example version
  url_launcher: ^6.2.1 # Example version
  cached_network_image: ^3.3.1 # Example version
  haptic_feedback: ^0.4.2 # Example version
  table_calendar: ^3.0.9 # Example version

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
